agendas: 
  path: ../agendas/agendas.api 
  storage: api 
 
agendas: 
  path: ../agendas/agendas.api 
  storage: api 
 
agendas: 
  path: ../agendas/agendas.api 
  storage: api 
 
agendas: 
  path: ../agendas/agendas.api 
  storage: api 
 
agendas: 
  path: ../agendas/agendas.api 
  storage: api 
 
agendas: 
  path: ../agendas/agendas.api 
  storage: api 
 
agendas: 
  path: ../agendas/agendas.api 
  storage: api 
 
agendas: 
  path: ../agendas/agendas.api 
  storage: api 
 
agenda: 
  path: ../agendas/agenda.csv 
  storage: csv 
 
agenda: 
  path: ../agendas/agenda.api 
  storage: api 
 
agenda: 
  path: ../agendas/agenda.api 
  storage: api 
 
agenda: 
  path: ../agendas/agenda.api 
  storage: api 
 
agenda: 
  path: ../agendas/agenda.api 
  storage: api 
 
agenda: 
  path: ../agendas/agenda.api 
  storage: api 
 
